### ISSUE TITLE
Failed to setup osate development environment with osate2_2021-03.setup

### ISSUE THREAD

**Issue by wchaoRealize** [osate/osate2#2768] opened 2022-03-07 03:50 UTC
**Summary**
When I run eclipse installer to install Eclipse IDE according to the guide "https://osate.org/setup-development.html", it comes with error 
"ERROR: org.eclipse.equinox.p2.metadata.repository code=1000 No repository found at https://download.eclipse.org/technology/epp/packages/2021-03/202103121200."
So I checked "https://download.eclipse.org/technology/epp/packages" manually and found installation packages of earlier version does not exist. 
By the way, the repository "https://xtexttools.libutzki.de/" also seems to have been invalid.
Whether the installation file "osate2_2021-03.setup" needs to be updated?
Any help would be greatly appreciated! Thank you

**Desktop (please complete the following information):**
 - OSATE Version: osate2_2021-03.setup
 - Operating System: windows 10 x64

**Comment by wchaoRealize** [comment] 2022-03-09 01:14
I tried to modify the version information of the eclipse in the setup file to "2021-09", and the build was successful.
By the way, the APIBaseline link "https://osate-build.sei.cmu.edu/download/osate/stable/2.10.1-vfinal/osate.repository-2.10.1.vfinal.zip" in the setup file is invalid. I have modified to "2.10.2".

**Comment by lwrage** [comment] 2022-03-09 16:59
It looks like you were using an old version of the setup file. The latest on master has 2.10.2, already for the baseline.
In general, it is better to discuss issues with the development environment setup on our google group. There you may get feedback from a wider range of users.

**Comment by lwrage** [comment] 2022-03-09 18:30
I was not able to reproduce the other issues using the current setup file.

**Comment by lwrage** [comment] 2022-03-21 22:06
We've switched to 2022-03 - closing.

**Closed by lwrage** 2022-03-21 22:06 UTC
Labels: resolution:not reproducible
