### ISSUE TITLE
OSATE allows aadl2 file extension for AADL files

### ISSUE THREAD

**Issue by Etienne13** [osate/osate2#2197] opened 2020-02-11 15:52 UTC
Note: this issue is actually difficult to reproduce on other examples than the one referenced bellow. I tried to reproduce it on simpler examples but I did not manage to.

## Summary

I use the example [here](https://se206.wp.imt.fr/files/2019/03/simple-latency-analysis.zip) during one of my courses. I ask students to complete the process implementation named control_application.impl. They have to add thread subcomponents, and connect them.

## Steps to Reproduce

1. Download the archive referenced above. Extract the content of the archive and import the project in it (File --> Import --> Existing project into workspace...)
2. Create the Structure diagram for the process implementation control_application.impl in software.aadl
3. From the textual editor, add a new thread in control_application.impl, say obst_detection2: thread obstacle_detection;

open the diagram of control_application.impl, obst_detection2 does not appear. Open the "Configure diagram" menu, obst_detection2 does not appear. Restart osate, and open the "Configure diagram" menu --> obst_detection2 does appear now.

## Environment

* **OSATE Version**: 2.7.0 but first noticed the issue in 2.5.3
* **Operating System**: Linux Ubuntu and Debian

**Comment by lwrage** [comment] 2020-02-11 17:11
New components are no longer automatically added to an existing diagram because it can destroy the layout if it was done manually, so that is not a bug. However, the new thread should show up in the "Configure Diagram" dialog and the outline view.

**Comment by philip-alldredge** [comment] 2020-02-11 21:13
@lwrage @Etienne13 
The root cause of this is that the graphical editor only monitors changes to files with the ".aadl" extension. The files in the project have a ".aadl2" extension. From looking at other parts of the OSATE code it appears that support for the "aadl2" extension is mixed. It's easy enough to fix it on the graphical editor side but there are other features in OSATE that assume an "aadl" extension.

**Comment by Etienne13** [comment] 2020-02-12 09:36
I tested with the aadl extension for my files and it works fine indeed. This also explains why I was not able to reproduce the issue after creating new aadl packages. Thanks for the information.

**Comment by philip-alldredge** [comment] 2020-02-12 13:31
@Etienne13 @lwrage since the text editor supports the aadl2 extension, I'm marking this as a GE bug to be fixed on the next release. However, I believe there are likely cases in other parts of OSATE which do not handle the "aadl2" extension.

**Comment by lwrage** [comment] 2020-02-12 21:01
That aadl2 file extension is a leftover from the early days of our AADL2 implementation. It's probably better if we remove it.

**Comment by philip-alldredge** [comment] 2020-02-12 21:54
That works for me. If that's the path forward, then we should remove the GE tag. The graphical editor's behavior is a side effect of the partial support in core.

**Closed** 2020-03-13 18:24 UTC
Labels: category:bug, core, importance:medium
