### ISSUE TITLE
Key binding conflict in graphical editor

### ISSUE THREAD

**Issue by AaronGreenhouse** [osate/osate2#1091] opened 2018-03-07 19:13 UTC
Ecipse/OSATE reports a key-binding conflict at startup.  This appears in the console and in the Eclipse error log.  On the console it reports

!MESSAGE A conflict occurred for CTRL+SHIFT+V:
Binding(CTRL+SHIFT+V,
	ParameterizedCommand(Command(org.eclipse.jdt.debug.ui.command.OpenFromClipboard,Open from Clipboard,
		Opens a Java element or a Java stack trace from clipboard,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@20fdd484,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+V,
	ParameterizedCommand(Command(org.osate.ge.goToAadlSource,Go to AADL Source,
		,
		Category(org.eclipse.core.commands.categories.autogenerated,Uncategorized,Commands that were either auto-generated or have no category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@3e0575a2,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)

The graphical editor is creating the conflict with the binding for goToAaadlSource.

This occurs on Windows.  Someone needs to check if it also occurs on MacOS and Linux.

**Comment by lwrage** [comment] 2018-07-02 15:18
duplicate of #1352

**Closed by lwrage** 2018-07-02 15:18 UTC
Labels: resolution:duplicate
