### ISSUE TITLE
Subcomponent category not correctly displayed in diagram

### ISSUE THREAD

**Issue by dblouin** [osate/osate2#1497] opened 2018-09-06 15:55 UTC
In the diagram of the attached test3 project, the subcomponent category is displayed as abstract while the subcomponent classifier is not abstract, but extends an abstract classifier. Note that strangely this only happens when the declarations are located in different files and different projects. See attached projects to reproduce.
[issue.zip](https://github.com/osate/osate2/files/2357758/issue.zip)

This occurs for OSATE 2.3.5 running on Windows 7.

**Comment by philip-alldredge** [comment] 2018-09-06 18:17
This issue was introduced in 2.3.0.
			
The use of LiveScopeResourceSetInitializer in DefaultAadlResourceService causes the issue. We need to determine what the root cause is and evaluate all uses of LiveScopeResourceSetInitializer and the live scope. Using XtextLiveScopeResourceSetProvider is likely the appropriate solution.

**Comment by philip-alldredge** [comment] 2018-09-07 14:42
The theory was that switching to XtextLiveScopeResourceSetProvider would fix the issue because it would have the proper project configuration. However, that is not the case. The same issue occurs when using a resource set provided by XtextLiveScopeResourceSetProvider.

**Comment by philip-alldredge** [comment] 2018-09-07 16:42
@dblouin @lwrage this is a duplicate of #1097. The work around is to add another file in the referenced project until this issue is resolved.

**Closed by philip-alldredge** 2018-09-07 16:42 UTC
Labels: category:bug, ge
