### ISSUE TITLE
OSATE 2.9.1 product should open in AADL perspective

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2#2621] opened 2021-03-15 10:58 UTC
**Summary**
When I download and open OSATE 2.9.1 product, I have to open the AADL perspective manually.

**Expected behavior**
Install opens in AADL perspective.

**Actual behavior**
See summary

**Steps To Reproduce**
Download OSATE 2.9.1 and launch it.

**Screenshots**

**Desktop (please complete the following information):**
 - OSATE Version: 2.9.1
 - Operating System:  Windows 10

**Additional context**

**Comment by lwrage** [comment] 2021-03-15 17:26
Duplicate of #2569. The workaround is described in the 2.9.1 release notes.

**Closed by lwrage** 2021-03-15 17:26 UTC
