### ISSUE TITLE
GE SVG Export isn't editable / high quality

### ISSUE THREAD

**Issue by sprocter** [osate/osate2#1461] opened 2018-08-17 15:37 UTC
## Summary

I have been using the graphical editor to make screenshots for a paper I'm writing, and SVG is ideal because it prints very clearly. Exported diagrams, however, do not render cleanly. Text labels, in particular, are blurry:

![screenshot from 2018-08-17 11-30-53](https://user-images.githubusercontent.com/1319948/44274788-15483e80-a211-11e8-9db3-c30af2975f70.png)

## Expected and Current Behavior

Expected: Text should be clearly readable, and fully scalable. Also ideal would be that the individual shapes are editable in an SVG editor like [inkscape](https://inkscape.org/en/)

Actual: Text is blurry. The entire image is rendered as one object, and so is not editable.

## Steps to Reproduce

1. Create an AADL model
2. Export an SVG version of the graphical view via right-clicking on the diagram and selecting "Export Diagram..."

## Environment

* **OSATE Version**: This happens in my development version, using the develop branch.
* **Operating System**: Linux (Ubuntu 16.04 LTS)

**Comment by philip-alldredge** [comment] 2018-08-17 15:47
Can you provide an SVG that is generated from your development environment? This behavior does not seem consistent with the behavior under windows.

**Comment by sprocter** [comment] 2018-08-17 22:51
Here's the .svg file: https://gist.github.com/sprocter/e99ff8f3308942f941f8a86802bb1f84

**Comment by philip-alldredge** [comment] 2018-08-18 02:47
The graphic is editable. In inkscape, it is possible to ungroup the object and move individual pieces. This seems to be consistent between platforms.

The font behavior differs between platform. The font-family differs between platforms. Also on windows, the text is exported as SVG text and is accordingly editable. On Ubuntu the text appears to be exported as an embedded PNG image.  This causes a large SVG file and low quality. 

To resolve, we'll need to dig into the behavior of the SVG exporter to determine the root cause. The graphical editor relies on Graphiti. Graphiti's SVG export capability uses Batik's SVGGraphics2D.

**Comment by philip-alldredge** [comment] 2018-09-21 15:07
If a migration to GEF5 is performed, then the SVG export could be reworked as part of that.

**Comment by philip-alldredge** [comment] 2021-07-06 17:16
Fixed by dbefc8b

**Closed by philip-alldredge** 2021-07-06 17:16 UTC
Labels: category:bug, ge, importance:medium, post_graphiti
