### ISSUE TITLE
End to end flow instance is not created if subprogram access connections are involved

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2#1941] opened 2019-08-08 20:34 UTC
See the end to end flow and the remote subprogram call from t2 to t1.
[Examples.txt](https://github.com/osate/osate2/files/3483565/Examples.txt)

**Comment by lwrage** [comment] 2019-08-08 21:26
Maybe caused by #676. E2e flow instantiation assumes there are only unidirectional connections in the instance model.

**Comment by lwrage** [comment] 2019-08-09 13:13
Likely duplicate of #643.

**Comment by AaronGreenhouse** [comment] 2019-10-18 16:39
Tried instantiating `Example19.impl`.  The end to end flow is created, and seems to be correct.  However, actually 2 end to end flows are created, and one of them seems spurious.

![Screen Shot 2019-10-18 at 12.36.19 PM.png](https://images.zenhubusercontent.com/5cc7040c07a4ab52d27abe58/de961361-4cad-4efa-ba4b-65b993b2e002)

I'm investigating the second end to end flow now.  Not sure what it is created, or if it even has anything to do with the original problem of subprogram access connections.

**Comment by AaronGreenhouse** [comment] 2019-10-18 18:03
The second end to end flow comes about because when looking for the connection instances that come out of flow `Flow_Sub` that match the `connections` list `[ac2]`, we end up with two connection instances.  This occurs as follows:

1. In `processFlowStep(ComponentInstance, EndToEndFlowInstance, Element, FlowImplementation, FlowIterator)` the method `collectionConnectionInstances()` is called.  The `connections` field contains one `Connection`, `"ac2"`, which is the connection that immediately follows `MyT1.Flow_Sub` in flow path `Flow2`.
2. Method `collectionConnectionInstances()` tests all the available connection instances using `testConnection()`.
3. The instance model has a semantic connection `"MyT1.CompAvg -> MyT2.ext_sub"` corresponding the connections `ac1` and `ac2`.
4. This connection matches in `testConnection()` because
* The first part of the method is designed to match any connection instance where that has `connections` as a **sublist** of the connection references.  `[ac2]` is a sublist of `[ac1, ac2]`.
* The directions of the flow and connection match
* The final part of the method is designed to check that the end points of the connection instance and flow match, but **only if the endpoint is a feature**.  As the end point of `"MyT1.CompAvg -> MyT2.ext_sub"` is a subprogram subcomponent, these check does nothing.

So I'm a bit confused why `testConnections()` operates the way it does.
* Why does it check for a sublist?  I would think you would want to check if the lists are identical.
* Why are only feature endpoints checked?  Is this an oversight, or there a reason for this?

It still seems to me that we do not want this second end to end flow.  The matching of this second connection instance doesn't make a lot of sense.

**Comment by lwrage** [comment] 2019-10-21 13:23
The connection instantiation is messed up. The ext_sub - shared_sub connection instances shouldn't be there and there should be an additional connection instance ext_sub -> CompAvg.

If I remove the subprogram the connections and flows are instantiated as expected.

**Comment by lwrage** [comment] 2019-10-21 13:46
We need a better test case for this issue with calls and connections via call parameters.

**Comment by AaronGreenhouse** [comment] 2019-10-22 16:34
Created a new issue for the connections problem and made this issue depend on it (Issue #2032)

**Comment by AaronGreenhouse** [comment] 2019-11-12 15:52
This seems to be fixed by #2032.  The bad "ext_sub - shared_sub" connection is gone, and the missing "ext_sub -> CompAvg" connection is now present.  There is one end to end flow instance created.

**Comment by lwrage** [comment] 2020-01-03 14:37
Fixed together with #2032

**Closed by lwrage** 2020-01-03 14:37 UTC
Labels: category:bug, core, importance:medium
