### ISSUE TITLE
units unresolved randomly

### ISSUE THREAD

**Issue by juli1** [osate/osate2#731] opened 2016-08-01 19:48 UTC
Working on OSATE since several hours and randomly, the time units are no longer recognized. This is totally random, I have no reliable way to reproduce this. But this is very inconvenient and impact the user experience.

**Comment by reteprelief** [comment] 2016-08-02 14:53
I have it too. It happens quite regularly on the Aircraft model that I brought over from the SAVI POC into AADL V2.

**Comment by lwrage** [comment] 2016-08-15 00:01
I've seen that, too. For me it has always resolved itself after saving or modifying the file. I guess it's related to us using a hand-written name resolver instead of the scoping mechanism for linking.

**Comment by lwrage** [comment] 2016-11-01 11:52
Copied form #749:

It is not uncommon when starting OSATE to find many Problems of the form

Couldn't resolve reference to UnitLiteral 'ms'.
Couldn't resolve reference to property definition 'Latency'. Property set name may be missing.

Repeated Project Clean... can often resolve this, but the result is nondeterministic. Sometimes 100 errors occur, sometimes a dozen, and often (but not always) it clears them all.

**Comment by lwrage** [comment] 2018-10-02 17:06
duplicate of #1009

**Closed by lwrage** 2018-10-02 17:06 UTC
Labels: category:bug, core, resolution:duplicate
