### ISSUE TITLE
Graphical editor is unusable on Ubuntu 22.04.

### ISSUE THREAD

**Issue by schwerdf** [osate/osate2#2811] opened 2022-05-31 15:29 UTC
**Summary**
Any attempt to use the new graphical editor on Ubuntu 22.04 causes OSATE to crash with a segfault.

**Steps To Reproduce**
Run OSATE on Ubuntu 22.04 and try to use the graphical editor:
* Trying to create a diagram on the "Resource Budget" example model produced [this](https://github.com/osate/osate2/files/8806567/CreateDiagram.log) error dump. 
* Trying to open an existing diagram on the "ARP4761" example model produced [this](https://github.com/osate/osate2/files/8806569/OpenDiagram.log) error dump.

**Desktop (please complete the following information):**
 - OSATE Version: 2.10.2 and 2.11.0-v20220503-1819 (the latter was used to produce the attached error dumps)
 - Operating System: Ubuntu 22.04

**Comment by lwrage** [comment] 2022-06-03 19:52
I was able to reproduce the JVM crash in a Wayland session. Workaround is to use an Xorg session, instead. See https://linuxconfig.org/how-to-enable-disable-wayland-on-ubuntu-22-04-desktop for instructions.
Looks like JavaFX doesn't work with Wayland, so the issue may go away with a future JavaFX update. 
Closing, as this is not a bug we can fix in OSATE.

**Closed by lwrage** 2022-06-03 19:52 UTC
Labels: resolution:upstream
