### ISSUE TITLE
User-defined properties show as text not lines in GE

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2#1680] opened 2019-02-04 17:35 UTC
When I Configure Diagram... and Add... standard binding properties, they show up as lines in the diagram.  However, when I Add... user-defined (property set) binding properties (and perhaps any user-defined reference properties), what appears in the diagram is a textual list of the property names rather than lines showing the relations between the two model elements.

## Environment

* **OSATE Version**: 2.3.7.vfinal
* **Operating System**: Windows 10

**Comment by philip-alldredge** [comment] 2019-02-04 17:38
Can you provide a complete example so it can be reproduced?

Philip Alldredge
Research Scientist
Rotorcraft Systems Engineering and Simulation Center
University of Alabama in Huntsville
VBRH A-4
256-824-4837
Philip.Alldredge@uah.edu

**Comment by stevevestal** [comment] 2019-04-02 16:19
I can reproduce this.  Attached is a figure of what I am seeing.  The properties are user-defined reference properties, specified on a system, referencing a subset of that system's subcomponents (this is not an inherit property).  I can email you the zipped project and point to the specific implementation declaration when you are ready.


![InnerBindingProperties](https://user-images.githubusercontent.com/3299870/55418765-edf07880-5538-11e9-9948-b907beaac8f5.png)

**Comment by philip-alldredge** [comment] 2019-05-07 20:57
@stevevestal  Please send me a model that reproduces this issue.

**Comment by stevevestal** [comment] 2019-05-07 21:07
Go to the Example_Utilization_Refined diagram and configure that diagram.  Three standard binding properties are checked, and those reference property values show up as dotted lines.  If you check the FASTAR::Inner_Processor_Binding, it will be displayed as text like a scalar valued property (such as Period) would be displayed rather than as a dotted line reference property.  It is displaying the property, and if you hover it will show you the value, but not in the same way (and as nicely) as standard reference properties.

**Comment by philip-alldredge** [comment] 2019-05-07 21:13
@stevevestal are you sending the model separately? It would be helpful to have any property sets that are being used as well. I don't have access to the FASTAR plugin.

**Comment by philip-alldredge** [comment] 2019-05-28 14:01
@stevevestal can you provide a model that reproduces this issue? It would be helpful to have a model along with any property sets being used. I don't have access to the model you referenced in the previous comment.

**Comment by stevevestal** [comment] 2019-05-28 21:30
Attached exported project has a simple example.  This one is not exactly the same symptom, but not displaying user-defined reference properties is the same issue.
[BindingGraphing.zip](https://github.com/osate/osate2/files/3229770/BindingGraphing.zip)

**Comment by philip-alldredge** [comment] 2019-05-29 17:10
The behavior is consistent between user-defined and standard properties. The actual issue is that we do not support showing reference properties from a component to its child. Enabling connection labels and shows that tsome of the properties are being shown. It is just the one from Hosts->proc which isn't being shown as a connection. It is just displayed as a label to indicate that it is set. I would need to look into the rationale for not showing the value in the label. I assume it has something to do with problems with long values. 

If I recall correctly there were practical issues which prevented representing this type of reference as a connection. In this case, would you expect the connection to originate at one of the borders of the "hosts" subcomponent?

![properties](https://user-images.githubusercontent.com/1376364/58576442-fba93e00-8209-11e9-8db2-aed3b27437e2.png)

The text for a Notes can be set from the Properties view. Double click the note and select the "Note" tab.

**Comment by stevevestal** [comment] 2019-05-29 17:22
Hmm, it wasn't showing dotted lines for all four of the bindings for me.  Has this been updated in OSATE 2.5?

Yes, the only visual I can think of is a dotted line between the outer box representing the system as a whole and the subcomponent box within that to which that system delegates whatever requirements are imposed on itself to some of its own subcomponents.

**Comment by philip-alldredge** [comment] 2019-05-29 17:33
No, nothing was changed with regards to this in 2.5.  If for some reason "hosts" wasn't being shown then apps would contain labels for the property associations.

**Comment by philip-alldredge** [comment] 2020-01-07 16:27
Closing due to be unable to reproduce. Please re-open if this is still an issue.

**Closed by philip-alldredge** 2020-01-07 16:27 UTC
Labels: ge, info needed
