### ISSUE TITLE
Flow latency analysis not working

### ISSUE THREAD

**Issue by rammierk** [osate/osate2#2892] opened 2024-04-19 05:20 UTC
I've been facing an issue with OSATE2 for a couple of weeks now. I am enrolled in the "Modeling System Architectures Using the Architecture Analysis Design Language (AADL)", 
and I am at Exercise-3: Running the Latency Analysis. I am able to create an instance of the system implementation MyCar.CruiseControl, with the complete flow specification as instructed, I am unable to generate the flow latency report. When I run Flow latency analysis, the analysis report is not generated.

Details:

I am using OSATE2 version 2.12.0.vfinal
 
Earlier in Exercise-2, I was able to successfully
1) Create an instance of the system implementation MyCar.parts 
2) Generate weight analysis report
Please see screenshot-1 (attached)
 
However in Exercise-3, I am able to create an instance of the system implementation MyCar.CruiseControl, with the complete flow specification as instructed, I am unable to generate the flow latency report. After clicking on the instance in AADL navigator, I am able to see the Analyses/Timing/Check flow latency option enabled in the menu. Please see screenshot-2 (attached). When I hit this option, I also get the Flow latency settings dialog. Please see screenshot-3 (attached). I leave all the defaults unchanged and hit OK.
But in the reports folder, the expected flow latency report is not generated. I think I should be seeing a “CarSystem_MyCar_CruiseControl_Instance_latency_AS_MF_DL_EQ.csv” file there. But only the previous weight analysis report “CarSystem_MyCar_parts_Instance_WeightAnalysis.csv” is seen there. Besides, in the Problems tab below it still shows the warnings of the previous weight analysis run. Please see screenshot-4 (attached)
 
Further, in the outline view when I right click on the system implementation MyCar.CruiseControl, I get the Analyses menu, but the Timing option is missing. Please see screenshot-5 (attached). Could this mean that the timing analysis isn't integrated into OSATE2, and that I may need to install and enable an analysis plugin for this to work?
 
I have retried several times, including deleting and recreating the instance, saving all files, exiting OSATE2 and relaunching, but it still shows the same behavior. 

5 screenshots attached

<img width="960" alt="1 - Exercise 3 error - Weight analysis OK" src="https://github.com/osate/osate2/assets/20660922/499da050-af0c-4939-b4e2-cf597dfec7c7">
<img width="960" alt="2 - Exercise 3 error - Timing analysis invoked" src="https://github.com/osate/osate2/assets/20660922/0b2543d1-efcb-4bfd-a525-879740f91a2d">
<img width="960" alt="3 - Exercise 3 error - Flow latency default settings" src="https://github.com/osate/osate2/assets/20660922/2e8393c8-6c36-4014-81e5-5b6cdbb22f89">
<img width="960" alt="4 - Exercise 3 error - Timing analysis report not generated" src="https://github.com/osate/osate2/assets/20660922/f1d62b3b-18a0-4020-8079-1db4d8361586">
<img width="960" alt="5- Exercise 3 error - Timing analysis option missing" src="https://github.com/osate/osate2/assets/20660922/3c675221-85ea-4e4b-bcf3-dd6cf722bf5a">

**Comment by lwrage** [comment] 2024-04-19 14:03
Could you share your six AADL files, please? You can add a new comment and attach the files to it..

**Comment by rammierk** [comment] 2024-04-19 17:19
Here they are, all 6 AADL files renamed to .txt files (since it doesn't permit to upload .aadl files)
1) [Sensors.txt](https://github.com/osate/osate2/files/15043581/Sensors.txt)
2) [Actuators.txt](https://github.com/osate/osate2/files/15043584/Actuators.txt)
3) [SoftwareApps.txt](https://github.com/osate/osate2/files/15043588/SoftwareApps.txt)
4)

**Comment by lwrage** [comment] 2024-04-22 13:23
This is a duplicate of #2885

**Closed by lwrage** 2024-04-22 13:23 UTC

**Comment by lwrage** [comment] 2024-04-23 13:57
The fix is available in the nightly build at https://osate-build.sei.cmu.edu/download/osate/testing/products/
