### ISSUE TITLE
Property Actual_Memory_Binding does not apply to org.osate.aadl2.instance.impl.ComponentInstanceImpl

### ISSUE THREAD

**Issue by passeris** [osate/osate2#2813] opened 2022-06-01 19:17 UTC
When performing a resource analysis (bounded), the error `Property Actual_Memory_Binding does not apply to org.osate.aadl2.instance.impl.ComponentInstanceImpl` shows in the error log. This happens when a system implementation has a bus subcomponent and a property declaration like the following:

```
properties

actual_memory_binding => (reference (ram)) applies to p.t1;
```

A simple model to reproduce this issue is listed below:

```
package pkg
public
	with SEI;

	memory ram
		properties
			memory_size => 7 bytes;
	end ram;

	memory implementation ram.i

	end ram.i;

	thread t1
	end t1;

	thread implementation t1.i
		properties
			stack_size=>1Gbyte;
	end t1.i;

	process p1
	end p1;

	process implementation p1.i
		subcomponents
			t1: thread t1.i;
	end p1.i;

	system s1
	end s1;
	
	bus CAN
		
	end CAN;
bus implementation CAN.impl
	
end CAN.impl;
	system implementation s1.i
		subcomponents
			ram: memory ram.i;
			p: process p1.i;
			bb: bus CAN.impl; -- COMMENT OUT THIS LINE IN ORDER FOR ANALYSIS TO WORK PROPERLY
		properties
			actual_memory_binding => (reference (ram)) applies to p.t1;
	end s1.i;
end pkg;
```

**Comment by lwrage** [comment] 2022-06-10 16:21
Duplicate of #2782

**Closed by lwrage** 2022-06-10 16:21 UTC
Labels: resolution:duplicate, category:bug, analyses

**Comment by passeris** [comment] 2022-06-11 12:32
I visited issue #2782 and copied the code as-is and ran the analysis. The error is still reported by OSATE. Is this a mistake in how we structure our AADL code i.e. a user error perhaps?

**Comment by lwrage** [comment] 2022-06-13 16:15
It's fixed in the upcoming release.
