### ISSUE TITLE
Feature group in end to end flow fails to create flow latency report

### ISSUE THREAD

**Issue by jpward** [osate/osate2#2475] opened 2020-10-06 19:15 UTC
## Summary

When executing Flow Latency Analysis on end to end flows containing feature group connections no results are generated and no information is provide as to why.

## Expected and Current Behavior

Flow Latency Analysis report should be generated or a popup as to why the report cannot succeed.

## Steps to Reproduce

1. Instantiate fg_bug_tst.impl
2. Select Instance from previous step and click "Sum latencies along flows" button, select OK
3. Note nothing happens

```aadl
package fg_bug
public

	feature group fg_socket
		features
 			output_sig: out data port;
			input_sig: in data port;
	end fg_socket;

	feature group fg_plug
		inverse of fg_socket
	end fg_plug;
	
    device fg_bug_tst_source
    	features
    		J1: feature group fg_plug;
    	flows
    		input_sig_source: flow source J1.input_sig;
    		output_sig_sink: flow sink J1.output_sig;
    end fg_bug_tst_source;
    device implementation fg_bug_tst_source.impl
	end fg_bug_tst_source.impl;
    
    system fg_bug
		features
			J2: feature group fg_socket;
		flows
			fg_bug_fpath: flow path J2.input_sig -> J2.output_sig;
	end fg_bug;

	system implementation fg_bug.impl
		flows
			fg_bug_fpath: flow path J2.input_sig -> J2.output_sig;
	end fg_bug.impl;
    
	
	system fg_bug_tst
	end fg_bug_tst;
	
	system implementation fg_bug_tst.impl
		subcomponents
			fg_bug: system fg_bug.impl;
			dts: device fg_bug_tst_source.impl;
		connections
			fg_bug_conn: feature group dts.J1 <-> fg_bug.J2;
		flows
			fg_bug_e2e: end to end flow dts.input_sig_source -> fg_bug_conn -> fg_bug.fg_bug_fpath -> fg_bug_conn -> dts.output_sig_sink;
	end fg_bug_tst.impl;
end fg_bug;
```

The following does create a report without the use of feature groups

```aadl
package fg_bug_no_fg
public
    device fg_bug_tst_source
    	features
    		output_sig: in data port;
			input_sig: out data port;
    	flows
    		input_sig_source: flow source input_sig;
    		output_sig_sink: flow sink output_sig;
    end fg_bug_tst_source;
    device implementation fg_bug_tst_source.impl
	end fg_bug_tst_source.impl;
    
    system fg_bug
    	features
    		output_sig: out data port;
			input_sig: in data port;
		flows
			fg_bug_fpath: flow path input_sig -> output_sig;
	end fg_bug;

	system implementation fg_bug.impl
		flows
			fg_bug_fpath: flow path input_sig -> output_sig;
	end fg_bug.impl;
    
	
	system fg_bug_tst
	end fg_bug_tst;
	
	system implementation fg_bug_tst.impl
		subcomponents
			fg_bug: system fg_bug.impl;
			dts: device fg_bug_tst_source.impl;
		connections
			fg_bug_conn1: port  dts.input_sig -> fg_bug.input_sig;
			fg_bug_conn2: port fg_bug.output_sig <-> dts.output_sig;
		flows
			fg_bug_e2e: end to end flow dts.input_sig_source -> fg_bug_conn1 -> fg_bug.fg_bug_fpath -> fg_bug_conn2 -> dts.output_sig_sink;
	end fg_bug_tst.impl;
end fg_bug_no_fg;
```

## Environment

* **OSATE Version**: OSATE2 2.8.0.vfinal
* **Operating System**:  Windows 10 Pro, 10.0.17763

**Comment by lwrage** [comment] 2020-10-08 15:36
Duplicate of #2423

**Closed by lwrage** 2020-10-08 15:36 UTC
Labels: analyses, category:bug, resolution:duplicate
