### ISSUE TITLE
Context Menu in Outline View Stops Working

### ISSUE THREAD

**Issue by brlarson** [osate/osate2#2110] opened 2019-12-15 01:28 UTC
## Summary
After being used for a while, right-click on items in the Outline window stops bringing up the context menu.  Then new instance models can't be created, but OSATE->Reinstantiate All Instance Models will re-create instance models that already exist.

## Expected and Current Behavior
Expected behavior:  right-click on a System Impl in the Outline view brings up a context menu.
Current behavior:  though not at first, right-click on Outline items does nothing.

This happens with both the 2.6.1 pre-built application, and running from sources.

## Steps to Reproduce
Use OSATE for at least a half-hour, then right-click an Outline view item.

I have been using Safety Analysis tools, particularly FTA, on the SafetyTutorial example with pre-built 2.6.1, and the Open PCA Pump model from sources.  I create instance models, and then run analyses upon them.

This has been happening for a while.  Reinstantiate All Instance Models does fine for existing instance models, and I've been restarting Eclipse when I need to make a new instance model.

## Environment

* **OSATE Version**: 3.6.1
* **Operating System**: macOS 10.14.6

**Comment by jjhugues** [comment] 2019-12-15 02:02
Duplicate of osate/osate2#2050
Work around is to close the text editor and reopen the file, no need to exit OSATE

**Closed by jjhugues** 2019-12-15 02:02 UTC
Labels: resolution:duplicate

**Comment by brlarson** [comment] 2019-12-15 13:16
Thank you.  I looked down through the list, but either didn't look far enough, or filtered for open issues.
I presume this is a general Eclipse thing, and not from any OSATE code.

On Dec 14, 2019, at 8:02 PM, Jerome Hugues <notifications@github.com<mailto:notifications@github.com>> wrote:


Duplicate of #2050<https://github.com/osate/osate2/issues/2050>
Work around is to close the text editor and reopen the file, no need to exit OSATE
